### ISSUE TITLE
onpressed method always throws exception `Null check operator used on a null value` 

### ISSUE THREAD

**Issue by imwangji** [Fliggy-Mobile/fbutton#20]
my simple code:
```
FButton(
                text: "开始",
                style: ButtonTextNormal,
                color: PrimaryPink,
                height: 48,
                alignment: Alignment.center,
                corner: FCorner.all(8),
                onPressed: () {
                  Get.to(() => const LoginPage());
                },
              )
```
always throw exception `Null check operator used on a null value`

```
======== Exception caught by gesture ===============================================================
The following _CastError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      _FButton.build.<anonymous closure> (package:fbutton_nullsafety/fbutton_nullsafety.dart:450:38)
#1      FControlState._updateState (package:fcontrol_nullsafety/fcontrol.dart:438:35)
#2      FControlState._controlGestureHandlerForState (package:fcontrol_nullsafety/fcontrol.dart:431:5)
#3      FControlState.build.<anonymous closure> (package:fcontrol_nullsafety/fcontrol.dart:264:11)
#4      TapGestureRecognizer.handleTapDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:581:61)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#6      TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:581:11)
#7      BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:287:5)
#8      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:265:7)
#9      GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:251:25)
#10     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:232:31)
(elided 10 frames from dart:async)
Handler: "onTapDown"
Recognizer: TapGestureRecognizer#54356
  debugOwner: GestureDetector
  state: possible
  button: 1
====================================================================================================
```

**Comment by error-code** [comment]
+1

**Comment by selyman** [comment]
add  highlightColor: Colors.white,
